### ISSUE TITLE
Modify solid heat conduction solver to handle 1D cases

### ISSUE THREAD

**Issue by nikoscham** [FEAScript/FEAScript-core#4]
## Overview

Currently, the ```solidHeatTransferScript``` solver supports only 2D simulations. We are planning to extend the capabilities of the solver to handle 1D cases.

## Tasks

- [x] Review and update the mesh generation and nodal numbering process for 1D meshes
- [x] Modify the ```thermalBoundaryConditionsScript``` for handling 1D cases
- [x] Modify the ```solidHeatTransferScript``` for handling 1D cases
- [x] Create a new tutorial for heat conduction in a large plane wall and compare the results with the analytical solution
