### ISSUE TITLE
Development of an MSH import tool

### ISSUE THREAD

**Issue by nikoscham** [FEAScript/FEAScript-core#5]
## Overview

This thread will monitor the development of a new tool for importing MSH files (created by [Gmsh](https://gmsh.info/))

## Tasks

- [x] Import of 2D mesh with quadrilateral elements
- [x] Import of 2D mesh triangular elements
- [x] Handle boundary conditions import from GMSH to FEAScript
- [x] Update nodal numbering process for 2D meshes with triangular elements
- [x] Update boundary conditions for 2D meshes with triangular elements
- [x] Create new tutorials with quadrilateral and triangular meshes

**Comment by sridhar-mani** [comment]
I have implemented a 2d quad cell reader for now from .msh v4.1 file. I am looking more into the format as i had previously worked on openfoam meshing and not used to this.

**Comment by nikoscham** [comment]
Thanks for the update and for all the work on this! Give me some time to perform some tests

**Comment by nikoscham** [comment]
I have created the following mesh (both triangular and quadrilateral mesh versions) in Gmsh for testing purposes.

[rect_mesh.zip](https://github.com/user-attachments/files/19655489/rect_mesh.zip)

**Comment by sridhar-mani** [comment]
> I have created the following mesh (both triangular and quadrilateral mesh versions) in Gmsh for testing purposes.
> 
> [rect_mesh.zip](https://github.com/user-attachments/files/19655489/rect_mesh.zip)

BTW - Also made a gpu branch where fully webgpu offloading has been implemented.

**Comment by sridhar-mani** [comment]
can you test if the mesh reading is as per the needed format and what next to develop?

**Comment by nikoscham** [comment]
> is the mesh reading is as per the needed format and what next to develop?

I am building gmsh example here: https://github.com/FEAScript/FEAScript-core/blob/main/examples/solidHeatTransferScript/HeatConduction2DFin/HeatConduction2DFinGmsh.html
I'll need a bit of time to go through your mesh import code. Thanks again!

**Comment by nikoscham** [comment]
The new tutorial (using a Gmsh-generated mesh) is here: https://feascript.com/tutorials/HeatConduction2DFinGmsh.html
Thanks a lot for the contribution!

**Comment by sridhar-mani** [comment]
Welcome, Hope we can expand this library to help others.
